from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1]
r=json.loads((ROOT/'docs/quality_audit.json').read_text(encoding='utf-8'))
rows=''.join(f'<tr><td>{escape(c["name"])}</td><td>{"Conferido" if c["passed"] else "Divergência"}</td></tr>' for c in r['checks'])
page='''<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Qualidade e uso gerencial · Observatório dos Leilões Minerais</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f3f6fa;color:#102a43;font:17px/1.65 system-ui,sans-serif}header,main{max-width:1120px;margin:auto;padding:28px}header{display:flex;justify-content:space-between;gap:20px}a{color:#1351b4}h1{font-size:clamp(30px,5vw,48px);line-height:1.15}h2{font-size:25px}section{background:white;padding:30px;border-radius:16px;margin:24px 0}table{width:100%;border-collapse:collapse}td,th{padding:12px;text-align:left;border-bottom:1px solid #dce3eb}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:20px}.card{padding:20px;background:#edf3fb;border-radius:12px}.warning{border-left:5px solid #bb7a00;padding:16px;background:#fff8e8}.small{font-size:14px;overflow-wrap:anywhere}.links{display:flex;gap:18px;flex-wrap:wrap}button{font:inherit;background:#1351b4;color:white;padding:10px 18px;border:0;border-radius:8px;cursor:pointer}summary{cursor:pointer;font-weight:600}strong{color:#123e66}</style>
<header><a href="index.html">← Voltar ao Observatório</a><span>CFEM até junho de 2026</span></header><main><h1>Da informação à decisão, com evidências.</h1><p>Saiba o que foi conferido, o que ainda precisa de revisão e como usar os resultados no trabalho.</p>
<section><h2>Três perguntas para orientar a análise</h2><div class="grid"><article class="card"><h3>O lance foi cumprido?</h3><p>Localize o resultado da rodada e os eventos de pagamento ou descumprimento. Saldo calculado não substitui conciliação financeira.</p><a href="index.html#rounds">Examinar as rodadas →</a></article><article class="card"><h3>A área seguiu em outro processo?</h3><p>Leia a cadeia de associações e os atos em ordem. O arquivamento do processo original pode coexistir com continuidade no sucessor.</p><a href="index.html#processes">Consultar uma trajetória →</a></article><article class="card"><h3>Há algo que merece conferência?</h3><p>Examine o período, o título, a guia e o recolhedor. Na PLG, considere o primeiro adquirente. Ausência de registro não comprova dívida.</p><a href="index.html#alerts">Examinar os casos →</a></article></div></section>
<section><h2>O que os números permitem afirmar</h2><p><strong>114 áreas com CFEM posterior:</strong> 101 comerciais e 13 da seleção social. O total nominal é <strong>R$ 6.526.131,24</strong>. Os marcos de acompanhamento diferem entre os grupos.</p><p class="warning"><strong>R$ 664,57 milhões é o saldo dos lances após descontar o não pagamento identificado.</strong> Não representa arrecadação bancária certificada. Na leitura cadastral por processo original, há 161 classificados com evidência de pagamento, 1.272 com não pagamento e 6.093 sem evidência suficiente nesse levantamento. Essa contagem por processo não pode ser subtraída diretamente das 7.528 arrematações por área e rodada.</p><p>Comparações fiscais usam 6.094 trajetórias comerciais com dados antes e depois. Os totais não medem efeito causal, e os tempos de observação podem ser diferentes.</p></section>
<section><h2>Conferência reproduzível dos totais</h2><p>CHECKCOUNT verificações computacionais confrontam registros, somas e contagens da mesma versão. Elas verificam consistência interna; não substituem a revisão dos documentos originais.</p><details><summary>Consultar todas as verificações</summary><table><thead><tr><th>Verificação</th><th>Resultado</th></tr></thead><tbody>CHECKROWS</tbody></table></details><p class="small">Identificador da versão dos dados: HASHVALUE</p><div class="links"><a href="docs/quality_audit.json" download>Baixar relatório de conferência</a><a href="methods/audit_snapshot.py" download>Baixar código Python</a><a href="docs/amostra_revisao.csv" download>Baixar amostra para revisão documental</a></div></section>
<section><h2>Como concluir uma revisão</h2><ol><li>Registre área, rodada, processo original, sucessor e pergunta investigada.</li><li>Consulte o documento que sustenta a classificação e sua data.</li><li>Separe a evidência encontrada da interpretação; registre as informações que faltam.</li><li>Encaminhe a questão à equipe competente e registre a conclusão e a fonte.</li></ol><p>O Observatório orienta a consulta. O registro e o encaminhamento institucional da decisão dependem dos procedimentos da ANM; não são realizados automaticamente nesta página.</p></section>
<section><h2>O que falta medir</h2><p>A amostra disponibilizada foi selecionada por rodada e situação, com semente fixa. Os campos de revisão estão vazios porque a validação independente ainda não foi realizada. Não há nota de precisão presumida.</p><div class="grid"><article class="card"><h3>Qualidade das classificações</h3><p>Revisores devem conferir vínculos, eventos e atribuição da CFEM, inclusive nos casos sem alerta. Registrar divergências e documentos utilizados.</p></article><article class="card"><h3>Benefício para o usuário</h3><p>Comparar tarefas equivalentes com e sem o painel: tempo, acerto da conclusão e consultas adicionais. Alternar a ordem para reduzir o efeito de aprendizagem.</p></article><article class="card"><h3>Conciliação e tempo</h3><p>Confrontar o saldo com pagamentos e comparar janelas equivalentes. Sem esses passos, não afirmar receita confirmada ou superioridade entre rodadas.</p></article></div></section><p class="small">Proposta analítica com dados abertos da ANM. Não constitui certificação de regularidade nem serviço oficialmente homologado.</p></main></html>'''
page=page.replace('CHECKCOUNT',str(len(r['checks']))).replace('CHECKROWS',rows).replace('HASHVALUE',r['snapshot_sha256'])
(ROOT/'qualidade.html').write_text(page,encoding='utf-8')
