from pathlib import Path
import json

OUT=Path('work'); docs=[]
P='https://www.planalto.gov.br/ccivil_03/'
N='Não verificado nas fontes consultadas.'
def add(id,title,kind,issuer,year,topic,url,article,summary,**kw):
    d=dict(id=id,title=title,type=kind,issuer=issuer,year=year,topic=topic,url=url,article=article,summary=summary,
           act=title,process=N,decision_date=N,publication_date=N,round='Geral',question=topic,
           command=summary,recipients='Conforme o dispositivo citado',deadline='Não se aplica a este registro',
           consulted='2026-09-26',status='Trecho pertinente consultado; conferir redação aplicável ao fato',
           interpretation='Fundamento de leitura; não certifica a situação de um processo individual.',pending=N,related=[],text_source='Resumo próprio; consultar o texto oficial no link.')
    d.update(kw);docs.append(d)
add('cf','Constituição Federal','Constituição','Assembleia Nacional Constituinte','1988','Recursos minerais',P+'constituicao/constituicao.htm','Arts. 20, IX e § 1º; 176','Recursos minerais pertencem à União; a exploração econômica e a compensação têm fundamento constitucional.')
add('codigo','Código de Mineração · Decreto-Lei 227/1967','Decreto-lei','Presidência da República','1967','Disponibilidade',P+'decreto-lei/del0227.htm','Arts. 26, 32 e 65','Prevê tratamento de áreas após o encerramento de direitos e procedimentos para aproveitamento mineral.')
add('plg','Lei 7.805/1989','Lei','Presidência da República','1989','PLG',P+'leis/l7805.htm','Arts. 1º a 3º','Institui a Permissão de Lavra Garimpeira. Outorga e licenciamento ambiental são condições próprias; seleção não equivale a permissão.')
add('7990','Lei 7.990/1989','Lei','Presidência da República','1989','CFEM: obrigação e aplicação',P+'leis/l7990.htm','Arts. 6º e 8º, §§ 1º e 2º','Distingue hipóteses de incidência e regras de uso dos recursos. As restrições de dívida e pessoal têm exceções expressas.',related=['8001','13540'])
add('8001','Lei 8.001/1990 · compilada','Lei','Presidência da República','1990','CFEM: apuração e distribuição',P+'leis/l8001compilado.htm','Art. 2º; art. 2º-A; art. 2º-F; Anexo','Define bases, sujeitos, partilha, transparência e alíquotas. Na PLG, o primeiro adquirente é sujeito passivo. A redação compilada não deve ser aplicada retroativamente.',related=['13540','14514','11659'])
add('13540','Lei 13.540/2017','Lei modificadora','Presidência da República','2017','CFEM: mudanças no tempo',P+'_ato2015-2018/2017/lei/l13540.htm','Arts. 1º e 2º; regras de vigência','Altera incidência, bases e partilha da CFEM. Use a redação do período; a partilha atual não é um retrato de todos os anos anteriores.',status='Dispositivos consultados por remissão no texto compilado da Lei 8.001',related=['8001'])
add('9406','Decreto 9.406/2018','Decreto','Presidência da República','2018','Disponibilidade',P+'_ato2015-2018/2018/decreto/d9406.htm','Arts. 45 e 46','Regulamenta a disponibilidade e a oferta pública. A seleção confere prioridade, sujeita às condições do procedimento.',related=['codigo','r24'])
add('r24','Resolução ANM 24/2020','Resolução','ANM','2020','Disponibilidade','https://www.gov.br/anm/pt-br/acesso-a-informacao/perguntas-frequentes/disponibilidade-de-areas','Referência normativa na orientação oficial da ANM','Orienta a leitura das etapas comerciais e do procedimento especial. Pagamento, requerimento e eventual retorno dependem do edital e dos atos posteriores.',status='Orientação oficial consultada; consolidação integral e alterações pendentes',pending='Recuperar texto consolidado e versões aplicáveis a cada rodada.',related=['9406','ed6'])
add('r103','Resolução ANM 103/2022','Resolução','ANM','2022','PLG e primeiro adquirente','https://www.gov.br/anm/pt-br/assuntos/noticias/aviso-anm-aos-primeiros-adquirentes-de-permissao-de-lavra-garimpeira','Cadastro Nacional do Primeiro Adquirente','O cadastro do primeiro adquirente é uma fonte necessária para investigar seu papel. Diferença entre titular e recolhedor não constitui erro automático.',related=['8001'])
add('ed6','6ª rodada · Edital 1/2022','Edital · recuperação pendente','ANM','2022','6ª rodada','https://sople.anm.gov.br/portalpublico','Edital definitivo e anexos','O portal oficial foi procurado, mas não respondeu por resolução de nome nesta consulta. Não substituímos o edital definitivo por minuta ou reprodução de terceiros.',round='6',process='48051.002854/2021-94',status='Inteiro teor definitivo não recuperado nesta conferência',pending='Recuperar edital final, anexos, alterações e homologação consolidada; conferir pesos e desempates.',related=['launch6','ata54','ret6'])
add('launch6','Lançamento da sexta rodada','Comunicação institucional','ANM','2022','6ª rodada','https://www.gov.br/anm/pt-br/anm-lanca-sexta-rodada-de-oferta-publica-de-areas-para-mineracao','Finalidade e público','A ANM apresentou a rodada como ação de formalização e ordenamento da mineração, dirigida a garimpeiros e cooperativas, para prioridade de requerer PLG.',round='6',publication_date='2022-09-14',interpretation='Contexto institucional; não substitui o edital.',related=['ed6'])
add('ret6','6ª rodada · retificação de prazo','Publicação no DOU','ANM','2023','6ª rodada','https://pesquisa.in.gov.br/imprensa/servlet/INPDFViewer?captchafield=firstAccess&data=28%2F08%2F2023&jornal=530&pagina=111','DOU, seção 3, p. 111','Os prazos tiveram retificação. A data do lançamento não deve ser usada como marco universal de todos os requerimentos.',round='6',publication_date='2023-08-28',related=['ed6'])
add('ata54','Ata da 54ª Reunião Ordinária Pública','Ata com voto e deliberação','Diretoria Colegiada da ANM','2023','Decisões administrativas','https://www.gov.br/anm/pt-br/composicao/diretoria-colegiada/reunioes-da-diretoria-colegiada/atas-da-rop/minuta-da-ata-da-54a-rop.pdf','Item 4.10, p. 16 do PDF','O voto propõe retificações e tratamento das áreas 7 e 11. A deliberação registrada é sobrestamento por pedido de vista do Diretor-Geral; o voto não foi tratado aqui como decisão aprovada.',round='6',process='48051.002854/2021-94',command='Sobrestamento por pedido de vista, no documento consultado.',status='Item e deliberação consultados; desfecho posterior não conferido',pending='Localizar deliberação posterior, Nota Técnica 6990/2023 (SEI 8885028) e Deliberação 45 (SEI 8715187).',related=['ed6','ret6'])
add('14514','Lei 14.514/2022','Lei modificadora','Presidência da República','2022','Distribuição',P+'_ato2019-2022/2022/lei/l14514.htm','Alterações da Lei 8.001; art. 25','Modifica regras dos municípios afetados e prevê efeitos temporais específicos. O enquadramento depende do ciclo de arrecadação.',related=['8001','11659'])
add('11659','Decreto 11.659/2023','Decreto','Presidência da República','2023','Distribuição',P+'_ato2023-2026/2023/decreto/d11659.htm','Arts. 2º a 6º','Detalha a parcela de 15% por afetação: ferrovias 55%, dutovias 3%, portos 7% e estruturas 35% dessa parcela. Prevê regras especiais e aplicação a partir do ciclo iniciado em maio/2023.',publication_date='2023-08-24',related=['14514','r143'])
add('r143','Resolução ANM 143/2023','Resolução · orientação oficial','ANM','2023','Distribuição','https://www.gov.br/anm/pt-br/acesso-a-informacao/perguntas-frequentes/cfem-afetados-2023','Fórmulas, elegibilidade e recursos','Os valores de cada município dependem de substância, modalidade e fatores de cálculo. A partilha nacional simples não prevê um repasse municipal.',pending='Conferir consolidação e alterações, incluindo a Resolução 234/2026, antes de calcular ciclos atuais.',related=['11659'])
add('r234','Resolução ANM 234/2026','Alteração normativa · pendente','ANM','2026','Distribuição','https://anmlegis.datalegis.net/action/TematicaAction.php?acao=abrirVinculos&cod_menu=11113&cod_modulo=405&cotematica=24066252','Remissão no catálogo oficial','Foi localizada referência a alteração para o ciclo 2026/2027. O inteiro teor não pôde ser recuperado nesta conferência; seus efeitos não foram implementados em cálculo.',status='Localizada; leitura integral pendente',related=['r143'])
add('dief','DIEF-CFEM · perguntas frequentes','Orientação institucional','ANM','2026','Declaração','https://www.gov.br/anm/pt-br/acesso-a-informacao/perguntas-frequentes/dief-cfem-perguntas-e-respostas-frequentes','Primeiro adquirente e declaração','A categoria primeiro adquirente corresponde à primeira aquisição sob PLG. Declaração, guia e pagamento são informações distintas.',related=['r103','8001'])
add('tcu2116','Acórdão 2.116/2024 · Plenário','Acórdão · síntese oficial consultada','TCU','2024','Controle externo','https://portal.tcu.gov.br/imprensa/noticias/agencia-nacional-de-mineracao-deve-adotar-medidas-para-melhorar-arrecadacao-e-prevenir-sonegacao-fiscal','Seção Encaminhamentos; link para inteiro teor','A comunicação do Tribunal relata determinações sobre monitoramento da arrecadação e planos para sistemas e estrutura. Esses achados não classificam automaticamente os processos do Observatório.',process='TC 005.747/2022-8',decision_date='2024-10-09',recipients='ANM; ANM e MME em medidas conjuntas, conforme cada comando',deadline='Síntese informa 60 e 120 dias para planos; contagem e itens exigem leitura do acórdão.',status='Síntese oficial lida; inteiro teor indisponível no extrator',pending='Conferir cada item e prazo no inteiro teor; não foi aferido cumprimento.',related=['tcuMonitor','lar'])
add('tcuMonitor','Monitoramento do Acórdão 2.116/2024','Processo de monitoramento','TCU','2025','Controle externo','https://conecta-tcu.apps.tcu.gov.br/tvp/77468309','Informações públicas do processo','O processo público tem por objeto acompanhar determinações e recomendações. Sua existência não comprova cumprimento nem descumprimento.',process='TC 000.757/2025-0',status='Objeto público consultado; peças e conclusão não conferidas',related=['tcu2116'])
add('lar','Lista de Alto Risco · setor mineral','Síntese de controle externo','TCU','2024','Controle externo','https://sites.tcu.gov.br/listadealtorisco/desenvolvimento_do_setor_de_mineracao.html','O que precisa ser feito; decisões recentes','Aponta fragilidades na fiscalização, em títulos e guias e na gestão de créditos. Cita os Acórdãos 1.368 e 2.116/2024; o Observatório oferece sinais para conferência, não diagnósticos de infração.',related=['tcu2116','tcu1368'])
add('tcu1368','Acórdão 1.368/2024 · Plenário','Acórdão · inteiro teor pendente','TCU','2024','Guias de utilização','https://pesquisa.apps.tcu.gov.br/redireciona/acordao-completo/ACORDAO-COMPLETO-2648751','Referência na Lista de Alto Risco','A referência oficial relaciona a decisão à emissão excepcional de guias. Comandos, destinatários específicos e prazos não foram extraídos do inteiro teor.',status='Referência oficial localizada; inteiro teor não recuperado',related=['lar'])
add('tce','Aplicação de CFEM em municípios','Jurisprudência · pendente','TCE-MG','2020','Aplicação','https://www.tce.mg.gov.br/noticia/Detalhe/1111624717','Informativo de Jurisprudência 216','Foi localizado registro oficial sobre aplicação municipal. Não se atribui à ANM obrigação municipal e não se extrai conclusão de irregularidade de caso individual.',status='Localizado; documento integral e atos posteriores pendentes',pending='Consultar decisão, município, processo e eventual monitoramento antes de afirmar comandos.')
add('bases','Bases de dados abertos da ANM','Catálogo de dados','ANM','2026','Dados','https://www.gov.br/anm/pt-br/acesso-a-informacao/dados-abertos/bases-de-dados','SOPLE, Cadastro Mineiro, CFEM e SIGMINE','As extrações de setembro/2026 alimentam as trajetórias; CFEM é acompanhada até junho/2026. Data de extração não altera a competência dos registros.')
add('rounds','Acervo de rodadas','Catálogo institucional','ANM','2026','Editais','https://www.gov.br/anm/pt-br/assuntos/disponibilidade-de-areas/rodadas','Páginas das rodadas','Ponto de consulta para editais e resultados. Páginas genéricas não substituem editais e homologações individuais.',pending='Consolidar versões e alterações documentais de todas as rodadas.')
add('marca','Logotipo e identidade da ANM','Referência de marca','ANM','2019','Identidade visual','https://www.gov.br/anm/pt-br/centrais-de-conteudos/anm/documentos/anexo-vii-padronizacao-visual/view','Anexo de padronização visual','O anexo encontrado especifica conteúdo a ser produzido para um manual; não certifica códigos cromáticos da marca. O JPEG existente foi inspecionado e preservado.',status='Imagem original inspecionada; manual cromático definitivo não recuperado')

claims=[
 ('Disponibilidade não equivale a liberação imediata','codigo,9406,r24','Rodadas','Regra geral; depende do ato e do edital.'),
 ('O lance vencedor não comprova recolhimento de CFEM','7990,8001','Panorama','Distinção entre prioridade sobre área e aquisição de bem mineral.'),
 ('Primeiro adquirente é sujeito passivo na PLG','8001,r103','6ª rodada','Art. 2º-A, II; não atribuir toda receita do adquirente a uma área.'),
 ('CFEM distribuída não demonstra gasto executado','8001,7990','CFEM','Partilha e aplicação são etapas distintas.'),
 ('Restrições de uso têm exceções legais','7990','Aplicação','Art. 8º, §§ 1º e 2º.'),
 ('Parcela afetada tem fatores específicos','11659,r143,14514','Distribuição','Não converter simulação didática em previsão municipal.'),
 ('Voto da 54ª ROP não equivale a decisão aprovada','ata54','Biblioteca','Item 4.10 registra pedido de vista.'),
 ('Monitoramento do TCU não prova cumprimento','tcuMonitor,tcu2116','Biblioteca','Apenas objeto processual conferido.'),
 ('Receita de leilão é estimada por premissa','bases','Panorama','Total dos lances menos não pagamentos identificados; falta conciliação bancária.'),
 ('CFEM posterior é associação temporal, não efeito causal','bases','Resultados','Janelas por ciclo, vínculos e exclusões preservados.'),
 ('Critérios finais da seleção social exigem edital definitivo','ed6,launch6,ata54','6ª rodada','Contexto e resultado cadastral disponíveis; pesos finais pendentes.')
]
payload=dict(consulted='2026-09-26',documents=docs,claims=[dict(id='A'+str(i+1),claim=a,sources=b.split(','),section=c,limit=d) for i,(a,b,c,d) in enumerate(claims)],gaps=[
 'Conciliação financeira dos lances: estimativa não é arrecadação confirmada.',
 'Inteiro teor definitivo da 6ª rodada, alterações e homologação consolidada: portal SOPLE indisponível na consulta.',
 'Revisão individual dos títulos e operações do primeiro adquirente no grupo social.',
 'Inteiros teores de acórdãos e monitoramentos; cumprimento de determinações não avaliado.',
 'Consolidação das alterações das Resoluções 24/2020 e 143/2023, inclusive ciclo 2026/2027.',
 'Distribuição por beneficiário e documentos orçamentários de aplicação ainda não integrados.',
 'Licenças ambientais e produção física efetiva não estão integradas.',
 'Manual definitivo de cores da ANM não recuperado: a paleta azul é uma escolha do produto.'
])
(OUT/'document_library.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2),encoding='utf-8')
print(len(docs),'documentos;',len(claims),'afirmações com fundamentos')
